CommandeLigne:
    type: entity
    table: commande_ligne
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        reference:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: Reference
        idProduit:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: ID_Produit
        qte:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: Qte
    lifecycleCallbacks: {  }
