Products:
    type: entity
    table: products
    id:
        idProduit:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID_Produit
            generator:
                strategy: IDENTITY
    fields:
        reference:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: Reference
        intitule:
            type: string
            nullable: true
            length: 72
            options:
                fixed: false
            column: Intitule
        resume:
            type: string
            nullable: true
            length: 124
            options:
                fixed: false
            column: Resume
        prix:
            type: decimal
            nullable: true
            precision: 6
            scale: 2
            column: Prix
        cheminimage:
            type: string
            nullable: true
            length: 81
            options:
                fixed: false
            column: CheminImage
        note:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: Note
        type:
            type: string
            nullable: true
            length: 15
            options:
                fixed: false
            column: Type
        etat:
            type: string
            nullable: true
            length: 16
            options:
                fixed: false
            column: Etat
    lifecycleCallbacks: {  }
